version: "3.8"
services:

  web:
    networks:
      - bhs
    image: hansen1416/bhs-vue
    ports:
      - 4600:8080
    volumes:
      - ${FRONTEND_SOURCE}:/app
    working_dir: /app
    command: ["npm", "run", "serve"]

  py-api:
    networks:
      - bhs
    image: hansen1416/bhs-py-api
    environment:
      - FLASK_ENV=development
    ports:
      - 4601:80
    volumes:
      - ${PY_API_SOURCE}:/app
      - ${SHARED_DATA}:/sharedvol # input/output images

  py-selenium:
    networks:
      - bhs
    image: hansen1416/bhs-py-selenium
    ports:
      - 4602:80
    volumes:
      - ${PY_SELENIUM_SOURCE}:/app

  cpp-stylize:
    networks:
      - bhs
    image: hansen1416/bhs-cpp-stylize
    # ports:
    #   - 4602:80
    volumes:
      - ${CPP_STYLIZE_OPT}:/opt
      - ${SHARED_DATA}:/sharedvol # c++ executive, pre-trained model, input/output images

networks:
  bhs:
    driver: bridge