version: "3.0"
services:
    # phaser:
    #     networks:
    #         - bhs
    #     image: hansen1416/bhs-phaser
    #     ports:
    #         - 46000:8080
    #     volumes:
    #         - ${PHASER_DIR}:/app
    #     command: ["npm", "start"]
    #     # command: ["tail", "-f", "/dev/null"]

    web:
      networks:
        - bhs
      image: hansen1416/bhs-vue
      ports:
        - 4600:8080
      volumes:
        - ${FRONTEND_SOURCE}:/app
        # - ${SHARED_DATA}:/app/public/img/sharedvol
      working_dir: /app
      command: ["npm", "run", "serve"]

    # nginx-static:
    #   networks:
    #     - bhs
    #   image: nginx:1.21.1-alpine
    #   ports:
    #     - 4602:80
    #   volumes:
    #     - ${SHARED_DATA}:/usr/share/nginx/html

    # py-api:
    #   networks:
    #     - bhs
    #   image: hansen1416/bhs-py-api
    #   environment:
    #     - FLASK_ENV=development
    #   ports:
    #     - 4601:80
    #   volumes:
    #     - ${PY_API_SOURCE}:/app
    #     - ${SHARED_DATA}:/sharedvol # input/output images
    #   command: ["python", "-u", "./wsserver.py"]

    py-websocket:
      networks:
        - bhs
      image: hansen1416/bhs-py-tornado
      ports:
        - 4601:4601
      volumes:
        - ${PY_TORNADO_SOURCE}:/app
      environment:
        - ALI_ACCESS_ID=${ALI_ACCESS_ID}
        - ALI_ACCESS_KEY=${ALI_ACCESS_KEY}
        - SMTP_USERNAME=${SMTP_USERNAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
      # command: ["python3", "-u", "./httpserver.py"]
      # command: ["tail", "-f", "/dev/null"]

    # py-cartoongan:
    #   networks:
    #     - bhs
    #   image: hansen1416/bhs-py-cartoongan
    #   # environment:
    #   #   - FLASK_ENV=development
    #   ports:
    #     - 65432:65432
    #   volumes:
    #     - ${PY_CARTOONGAN}:/app
    #   command: ["python", "-u", "./app-server.py", "65432"]

    # py-selenium:
    #   networks:
    #     - bhs
    #   image: hansen1416/bhs-py-selenium
    #   ports:
    #     - 4602:80
    #   volumes:
    #     - ${PY_SELENIUM_SOURCE}:/app

    # cpp-cartoongan:
    #   networks:
    #     - bhs
    #   image: hansen1416/bhs-cpp-cartoongan
    #   ports:
    #     - 4602:4602
    #   # volumes:
    #     # - ${CPP_STYLIZE_OPT}:/opt
    #     # - ${SHARED_DATA}:/sharedvol 
    #     # c++ executive, pre-trained model, input/output images
    #   environment:
    #     - ALI_ACCESS_ID=${ALI_ACCESS_ID}
    #     - ALI_ACCESS_KEY=${ALI_ACCESS_KEY}

networks:
    bhs:
        driver: bridge
