apiVersion: v1
kind: Service
metadata:
  name: cpp-stylize
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: bhs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-stylize
spec:
  selector:
    matchLabels:
      app: bhs
  template:
    metadata:
      labels:
        app: bhs
    spec:
      containers:
      - name: cpp-stylize
        image: hansen1416/bhs-cpp-stylize
        livenessProbe:
          tcpSocket:
            port: 8888
          # periodSeconds: 1
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: /sharedvol
          name: pvc
        resources:
          limits:
            memory: 1Gi
            cpu: "0.25"
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: bhs-media-claim
          readOnly: false