apiVersion: v1
kind: Pod
metadata:
  name: cpp-stylize
# This is the pod template
spec:
  containers:
  - name: cpp-stylize
    image: hansen1416/bhs-cpp-stylize
    livenessProbe:
      tcpSocket:
        port: 8888
    ports:
    - containerPort: 8888
      protocol: TCP
    # volumeMounts:
    # - mountPath: /sharedvol
    #   name: pvc
    resources:
      limits:
        memory: 1Gi
        cpu: "0.25"
  restartPolicy: OnFailure
  # volumes:
  # - name: pvc
  #   persistentVolumeClaim:
  #     claimName: bhs-media-claim
  #     readOnly: false
# The pod template ends here