apiVersion: v1
kind: Service
metadata:
  name: tornado-cartoongan
spec:
  type: LoadBalancer
  ports:
    - port: 4601
      nodePort: 30001
  selector:
    app: bhs-tornado-cartoongan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornado-cartoongan
spec:
  selector:
    matchLabels:
      app: bhs-tornado-cartoongan
  template:
    metadata:
      labels:
        app: bhs-tornado-cartoongan
    spec:
      containers:
      - name: tornado-cartoongan
        image: hansen1416/bhs-py-tornado
        env:
        - name: ALI_ACCESS_ID
          value: "LTAI5tLwV38wLDsnsxKEdX3f"
        - name: ALI_ACCESS_KEY
          value: "vC8Uv3jophlVnRSkNBWkqTkp9fL9F7"
        livenessProbe:
          httpGet:
            path: /health
            port: 4601
          periodSeconds: 5
        ports:
        - containerPort: 4601
        # volumeMounts:
        # - mountPath: /sharedvol
        #   name: pvc
        resources:
          limits:
            memory: 1Gi
            cpu: "0.5"
      # volumes:
      # - name: pvc
      #   persistentVolumeClaim:
      #     claimName: bhs-media-claim
      #     readOnly: false